blank_issues_enabled: false
contact_links:
    - name: âœ¨ Feature Request
      url: https://github.com/apex/apex/discussions/categories/feature-requests?discussions_q=is%3Aopen+category%3A%22Feature+Requests%22+sort%3Atop
      about: Share and vote on feature requests for Apex
    - name: ğŸ‘‹ Apex Discord
      url: https://discord.gg/apex
      about: Join our Discord community for discussions and support
    - name: â“ Other Questions?
      url: https://x.com/sdrzn
      about: Contact the developer on X @sdrzn for other inquiries
